<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('employees', function (Blueprint $table) {
            $table->id();

            // === RELASI OPSIONAL KE REKRUTMEN ===
            $table->foreignId('applicant_biodata_id')
                ->nullable()
                ->constrained('applicant_biodatas') // fix BUG-1
                ->nullOnDelete();

            // === RELASI WAJIB ===
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('school_id')->constrained()->cascadeOnDelete();
            $table->foreignId('employee_category_id')->constrained();
            $table->foreignId('education_level_id')->constrained(); // pendidikan terakhir pegawai

            // === DATA PRIBADI (wajib ada, tidak rely ke applicant_biodatas) ===
            $table->string('full_name');
            $table->string('ktp', 16)->unique();
            $table->enum('gender', ['L', 'P']);
            $table->string('birthplace')->nullable();
            $table->date('birthday');
            $table->enum('marital_status', ['single', 'married', 'widowed', 'divorced', 'separated']);
            $table->string('religion')->nullable();
            $table->string('address')->nullable();
            $table->string('phone', 20)->nullable();
            $table->string('email')->nullable()->unique();
            $table->string('photo_path')->nullable();

            // === DATA KEPEGAWAIAN ===
            $table->date('join_date');
            $table->string('status')->default('probation')->index();
            // probation | active | inactive | resigned | terminated

            // === NIPY (generated by scheduler) ===
            $table->string('nipy', 20)->nullable()->unique();
            $table->timestamp('nipy_generated_at')->nullable();

            // === PROBATION ===
            $table->date('probation_end_date');

            $table->timestamps();
            $table->softDeletes(); // tambah: untuk non-destructive delete
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('employees');
    }
};
